[project]
name = "presenter-agent"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "livekit>=1.0.10",
    "livekit-agents[openai,silero]>=1.1.3",
    "pytest>=8.4.1",
    "xaibo[livekit,openai,webserver]>=0.1.9",
]
